<?php
/**
 * @file
 * Contains myoneclick.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\commerce_cart\Form\AddToCartFormInterface;
use Drupal\commerce_product\Entity\Product;
use Drupal\commerce_product\Entity\ProductVariation;
use Drupal\Core\Url;
use Drupal\Component\Serialization\Json;


/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function myoneclick_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_state->getBuildInfo()['callback_object'] instanceof AddToCartFormInterface) {
    $storage = $form_state->getStorage();
    if ($storage['view_mode'] == 'full') {
      /** @var Product $product */
      $product = $storage['product'];
      /** @var ProductVariation[] $product_variations */
      $product_variations = $product->getVariations();
      $product_variation = $product_variations[0];
      $qty = $product_variation->get('field_qty')->getValue();
      if (isset($qty[0]['value']) && $qty[0]['value'] > 0) {
        $form['actions']['buy_one_click'] = myoneclick_get_link_element($product->id());
        $form['actions']['buy_one_click']['#weight'] = $form['actions']['submit']['#weight'] + 0.1;
      }
    }
  }
}


/**
 * @param $product_id
 * @return array
 */
function myoneclick_get_link_element($product_id) {
  $myoneclick_config = \Drupal::config('myoneclick.settings');
  $element = [
    '#type' => 'link',
    '#title' => $myoneclick_config->get('popup.button_name'),
    '#url' => Url::fromRoute('myoneclick.form', ['commerce_product' => $product_id]),
    '#options' => [
      'attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'modal',
        'data-dialog-options' => $myoneclick_config->get('popup.dialog_options'),
      ]
    ],
    '#attached' => ['library' => ['core/drupal.dialog.ajax']],
  ];
  $dialog_options = $myoneclick_config->get('popup.dialog_options');
  $dialog_options = Json::decode($dialog_options);
  foreach ($dialog_options as $dialog_option_name => $dialog_option) {
    if (in_array($dialog_option_name, ['show', 'hide'])) {
      foreach ($dialog_option as $name => $value) {
        if ($name == 'effect') {
          $element['#attached']['library'][] = 'core/jquery.ui.effects.' . $value;
        }
      }
    }
  }
  return $element;
}