<?php
/**
 * @file
 * Contains myoneclick.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\commerce_cart\Form\AddToCartFormInterface;
use Drupal\commerce_product\Entity\Product;
use Drupal\commerce_product\Entity\ProductVariation;
use Drupal\Core\Url;
use Drupal\Component\Serialization\Json;
use Drupal\Core\Messenger\MessengerInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_html().
 */
function myoneclick_preprocess_html(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'myoneclick.checkout_page') {
    $variables['attributes']['class'][] = Html::cleanCssIdentifier('page--checkout-one-click');
  }
}


/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function myoneclick_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_state->getBuildInfo()['callback_object'] instanceof AddToCartFormInterface) {
    $config = Drupal::config('myoneclick.settings');
    if ($config->get('load_popup.addtocart')) {
      $view_modes = $config->get('load_popup.addtocart_view_modes');
      $storage = $form_state->getStorage();
      if (in_array($storage['view_mode'], $view_modes)) {
        $logic = $config->get('load_popup.logic');
        /** @var Product $product */
        $product = $storage['product'];
        /** @var ProductVariation[] $product_variations */
        $product_variations = $product->getVariations();
        $product_variation = $product_variations[0];
        $price = $product_variation->getPrice();

        $is_availability = TRUE;
        if (method_exists($product, 'isAvailability')) {
          $is_availability = $product->isAvailability();
        }
        \Drupal::moduleHandler()
          ->alter('myoneclick_is_availability', $product, $is_availability);

        if ($is_availability && !$price->isZero()) {
          if ($logic == 'popup') {
            $form['actions']['buy_one_click'] = myoneclick_get_link_element($product->id());
          }
          elseif ($logic == 'page') {
            $form['actions']['buy_one_click'] = $form['actions']['submit'];
            unset($form['actions']['buy_one_click']['#ajax']);
            $form['actions']['buy_one_click']['#value'] = $config->get('popup.button_name');

            // class
            if (!empty($form['actions']['buy_one_click']['#attributes']['class'])) {
              foreach ($form['actions']['buy_one_click']['#attributes']['class'] as $key => $class) {
                if ($class == 'button--add-to-cart') {
                  unset($form['actions']['buy_one_click']['#attributes']['class'][$key]);
                }
              }
            }
            $form['actions']['buy_one_click']['#attributes']['class'][] = 'button--buy-one-click';

            $form['#submit'][] = 'myoneclick_logic_page_submit';
            $form['actions']['buy_one_click']['#submit'][] = 'myoneclick_logic_page_submit';
          }
          $form['actions']['buy_one_click']['#weight'] = $form['actions']['submit']['#weight'] + 0.1;
        }
      }
    }
  }
}


function myoneclick_logic_page_submit(array $form, FormStateInterface &$form_state) {
  \Drupal::messenger()->deleteByType(MessengerInterface::TYPE_STATUS);
  $form_state->setRedirect('myoneclick.checkout_page', ['commerce_order' => $form_state->get('cart_id')]);
}

/**
 * @param $product_id
 * @return array
 */
function myoneclick_get_link_element($product_id) {
  $myoneclick_config = \Drupal::config('myoneclick.settings');
  $element = [
    '#type' => 'link',
    '#title' => $myoneclick_config->get('popup.button_name'),
    '#url' => Url::fromRoute('myoneclick.form', ['commerce_product' => $product_id]),
    '#options' => [
      'attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'modal',
        'data-dialog-options' => $myoneclick_config->get('popup.dialog_options'),
      ]
    ],
    '#attached' => ['library' => ['core/drupal.dialog.ajax']],
  ];
  $dialog_options = $myoneclick_config->get('popup.dialog_options');
  $dialog_options = Json::decode($dialog_options);
  foreach ($dialog_options as $dialog_option_name => $dialog_option) {
    if (in_array($dialog_option_name, ['show', 'hide'])) {
      foreach ($dialog_option as $name => $value) {
        if ($name == 'effect') {
          $element['#attached']['library'][] = 'core/jquery.ui.effects.' . $value;
        }
      }
    }
  }
  return $element;
}


/**
 * Implements hook_theme().
 */
function myoneclick_theme() {
  return [
    'myoneclick_form' => [
      'render element' => 'form',
    ],
    'myoneclick_checkout_page_form' => [
      'render element' => 'form',
    ],
  ];
}
